node {
   
   stage('SCM'){
     // git clone
	 git 'https://github.com/openmrs/openmrs-core.git'
   }
   
   stage('build the package') {
     // mvn package
	 sh label: '', script: 'mvn package'
   }
   
   //stage('archival') {
     // archiving artifacts
	// archive 'target/*.jar'    --> comment the stage
   //}
}