node {
   
   stage('SCM'){
     // git clone
	 git 'https://github.com/hemanthvarmap/spring-petclinic.git'
   }
   
   stage('build the package') {
     // mvn package
	 sh label: '', script: 'mvn package'
   }
   
   stage('archival') {
     // archiving artifacts
	 archive 'target/*.jar'
   }
   stage('show test results'){
   junit 'target/surefire-reports/*.xml'
   }
}